server {
    listen 80;
    listen [::]:80;

    server_name volleyball-khpk.khmelnytskyi.ua www.volleyball-khpk.khmelnytskyi.ua;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://volleyball-khpk.khmelnytskyi.ua$request_uri;
    }
}
